package org.mozilla.javascript;

import p012ch.qos.logback.core.joran.action.ActionConst;

/* renamed from: org.mozilla.javascript.ed */
public final class Token {
    /* renamed from: a */
    public static String m6625a(int i) {
        switch (i) {
            case -1:
                return "ERROR";
            case 0:
                return "EOF";
            case 1:
                return "EOL";
            case 2:
                return "ENTERWITH";
            case 3:
                return "LEAVEWITH";
            case 4:
                return "RETURN";
            case 5:
                return "GOTO";
            case 6:
                return "IFEQ";
            case 7:
                return "IFNE";
            case 8:
                return "SETNAME";
            case 9:
                return "BITOR";
            case 10:
                return "BITXOR";
            case 11:
                return "BITAND";
            case 12:
                return "EQ";
            case 13:
                return "NE";
            case 14:
                return "LT";
            case 15:
                return "LE";
            case 16:
                return "GT";
            case 17:
                return "GE";
            case 18:
                return "LSH";
            case 19:
                return "RSH";
            case 20:
                return "URSH";
            case 21:
                return "ADD";
            case 22:
                return "SUB";
            case 23:
                return "MUL";
            case 24:
                return "DIV";
            case 25:
                return "MOD";
            case 26:
                return "NOT";
            case 27:
                return "BITNOT";
            case 28:
                return "POS";
            case 29:
                return "NEG";
            case 30:
                return "NEW";
            case 31:
                return "DELPROP";
            case 32:
                return "TYPEOF";
            case 33:
                return "GETPROP";
            case 34:
                return "GETPROPNOWARN";
            case 35:
                return "SETPROP";
            case 36:
                return "GETELEM";
            case 37:
                return "SETELEM";
            case 38:
                return "CALL";
            case 39:
                return "NAME";
            case 40:
                return "NUMBER";
            case 41:
                return "STRING";
            case 42:
                return ActionConst.NULL;
            case 43:
                return "THIS";
            case 44:
                return "FALSE";
            case 45:
                return "TRUE";
            case 46:
                return "SHEQ";
            case 47:
                return "SHNE";
            case 48:
                return "REGEXP";
            case 49:
                return "BINDNAME";
            case 50:
                return "THROW";
            case 51:
                return "RETHROW";
            case 52:
                return "IN";
            case 53:
                return "INSTANCEOF";
            case 54:
                return "LOCAL_LOAD";
            case 55:
                return "GETVAR";
            case 56:
                return "SETVAR";
            case 57:
                return "CATCH_SCOPE";
            case 58:
                return "ENUM_INIT_KEYS";
            case 59:
                return "ENUM_INIT_VALUES";
            case 60:
                return "ENUM_INIT_ARRAY";
            case 61:
                return "ENUM_NEXT";
            case 62:
                return "ENUM_ID";
            case 63:
                return "THISFN";
            case 64:
                return "RETURN_RESULT";
            case 65:
                return "ARRAYLIT";
            case 66:
                return "OBJECTLIT";
            case 67:
                return "GET_REF";
            case 68:
                return "SET_REF";
            case 69:
                return "DEL_REF";
            case 70:
                return "REF_CALL";
            case 71:
                return "REF_SPECIAL";
            case 72:
                return "YIELD";
            case 74:
                return "DEFAULTNAMESPACE";
            case 75:
                return "ESCXMLATTR";
            case 76:
                return "ESCXMLTEXT";
            case 77:
                return "REF_MEMBER";
            case 78:
                return "REF_NS_MEMBER";
            case 79:
                return "REF_NAME";
            case 80:
                return "REF_NS_NAME";
            case 81:
                return "TRY";
            case 82:
                return "SEMI";
            case 83:
                return "LB";
            case 84:
                return "RB";
            case 85:
                return "LC";
            case 86:
                return "RC";
            case 87:
                return "LP";
            case 88:
                return "RP";
            case 89:
                return "COMMA";
            case 90:
                return "ASSIGN";
            case 91:
                return "ASSIGN_BITOR";
            case 92:
                return "ASSIGN_BITXOR";
            case 93:
                return "ASSIGN_BITAND";
            case 94:
                return "ASSIGN_LSH";
            case 95:
                return "ASSIGN_RSH";
            case 96:
                return "ASSIGN_URSH";
            case 97:
                return "ASSIGN_ADD";
            case 98:
                return "ASSIGN_SUB";
            case 99:
                return "ASSIGN_MUL";
            case 100:
                return "ASSIGN_DIV";
            case 101:
                return "ASSIGN_MOD";
            case 102:
                return "HOOK";
            case 103:
                return "COLON";
            case 104:
                return "OR";
            case 105:
                return "AND";
            case 106:
                return "INC";
            case 107:
                return "DEC";
            case 108:
                return "DOT";
            case 109:
                return "FUNCTION";
            case 110:
                return "EXPORT";
            case 111:
                return "IMPORT";
            case 112:
                return "IF";
            case 113:
                return "ELSE";
            case 114:
                return "SWITCH";
            case 115:
                return "CASE";
            case 116:
                return "DEFAULT";
            case 117:
                return "WHILE";
            case 118:
                return "DO";
            case 119:
                return "FOR";
            case 120:
                return "BREAK";
            case 121:
                return "CONTINUE";
            case 122:
                return "VAR";
            case 123:
                return "WITH";
            case 124:
                return "CATCH";
            case 125:
                return "FINALLY";
            case 126:
                return "VOID";
            case 127:
                return "RESERVED";
            case 128:
                return "EMPTY";
            case 129:
                return "BLOCK";
            case 130:
                return "LABEL";
            case 131:
                return "TARGET";
            case 132:
                return "LOOP";
            case 133:
                return "EXPR_VOID";
            case 134:
                return "EXPR_RESULT";
            case 135:
                return "JSR";
            case 136:
                return "SCRIPT";
            case 137:
                return "TYPEOFNAME";
            case 138:
                return "USE_STACK";
            case 139:
                return "SETPROP_OP";
            case 140:
                return "SETELEM_OP";
            case 141:
                return "LOCAL_BLOCK";
            case 142:
                return "SET_REF_OP";
            case 143:
                return "DOTDOT";
            case 144:
                return "COLONCOLON";
            case 145:
                return "XML";
            case 146:
                return "DOTQUERY";
            case 147:
                return "XMLATTR";
            case 148:
                return "XMLEND";
            case 149:
                return "TO_OBJECT";
            case 150:
                return "TO_DOUBLE";
            case 151:
                return "GET";
            case 152:
                return "SET";
            case 153:
                return "LET";
            case 154:
                return "CONST";
            case 155:
                return "SETCONST";
            case 157:
                return "ARRAYCOMP";
            case 158:
                return "LETEXPR";
            case 159:
                return "WITHEXPR";
            case 160:
                return "DEBUGGER";
            case 161:
                return "COMMENT";
            case 162:
                return "GENEXPR";
            default:
                throw new IllegalStateException(String.valueOf(i));
        }
    }
}
